nodeLinker: node-modules

npmScopes:
  navikt:
    npmRegistryServer: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN:-}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
