apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syfosmmanuell
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
  annotations:
    nais.io/read-only-file-system: 'false'
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - 'https://syfosmmanuell.dev.adeo.no/callback'
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/syfosmmanuell/teamsykmelding
        mountPath: /secrets/syfosmmanuell
  webproxy: true
  ingresses:
    - 'https://syfosmmanuell.dev.adeo.no'
  env:
    - name: AAD_REDIRECT_URL
      value: https://syfosmmanuell.dev.adeo.no/callback
    - name: DOWNSTREAM_API_URL
      value: https://syfosmmanuell-backend.nais.preprod.local/
    - name: GRAPH_API_SCOPES
      value: https://graph.microsoft.com/.default
    - name: MODIA_CONTEXT_URL
      value: https://modiacontextholder-q1.dev.adeo.no
    - name: SYFOSMMANUELL_BACKEND_SCOPE
      value: dev-fss.teamsykmelding.syfosmmanuell-backend
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
