apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syfosmmanuell
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
    sidecar:
      enabled: true
  ingresses:
    - 'https://syfosmmanuell.dev.intern.nav.no'
  env:
    - name: DOWNSTREAM_API_URL
      value: https://syfosmmanuell-backend.dev.intern.nav.no/
    - name: MODIA_CONTEXT_SCOPE
      value: api://dev-fss.personoversikt.modiacontextholder-q1/.default
    - name: MODIA_CONTEXT_URL
      value: https://modiacontextholder-q1.dev-fss-pub.nais.io
    - name: SYFOSMMANUELL_BACKEND_SCOPE
      value: dev-gcp.teamsykmelding.syfosmmanuell-backend
    - name: NEXT_PUBLIC_ENVIRONMENT
      value: dev
