apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfosmmanuell:{{tag}}"
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  webproxy: false
  ingresses:
    - "https://syfosmmanuell.nais.preprod.local"
  env:
    - name: NODE_ENV
      value: preprod