apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syfosmmanuell
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: { { image } }
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/syfosmmanuell
        mountPath: /secrets/azuread/syfosmmanuell
      - kvPath: /azuread/data/dev/creds/syfosmmanuell-backend
        mountPath: /secrets/azuread/syfosmmanuell-backend
  webproxy: true
  ingresses:
    - 'https://syfosmmanuell.nais.preprod.local'
  env:
    - name: AAD_DISCOVERY_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: AAD_REDIRECT_URL
      value: https://syfosmmanuell.nais.preprod.local/callback
    - name: DOWNSTREAM_API_PREFIX
      value: backend
    - name: DOWNSTREAM_API_HOST
      value: http://syfosmmanuell-backend/
    - name: REDIS_HOST
      value: syfosmmanuell-redis.default.svc.nais.local
    - name: REDIS_PORT
      value: 6379

