apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfosmmanuell:{{tag}}"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/syfosmmanuell
        mountPath: /secrets/azuread/syfosmmanuell
      - kvPath: /azuread/data/prod/creds/syfosmmanuell-backend
        mountPath: /secrets/azuread/syfosmmanuell-backend
  webproxy: true
  ingresses:
    - "https://syfosmmanuell.nais.adeo.no"
  env:
    - name: AAD_DISCOVERY_URL
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: AAD_REDIRECT_URL
      value: https://syfosmmanuell.nais.adeo.no/callback
    - name: DOWNSTREAM_API_PREFIX
      value: backend
    - name: DOWNSTREAM_API_HOST
      value: http://syfosmmanuell-backend/