apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syfosmmanuell
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
  annotations:
    nais.io/read-only-file-system: 'false'
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 384Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
            # 0000-GA-SYFO-SENSITIV geografisk tilgang til sykmeldinger
          - id: "100e88eb-79af-4136-8bfe-f79b32021f43"
    sidecar:
      enabled: true
  ingresses:
    - 'https://syfosmmanuell.intern.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: syfosmmanuell-backend
      external:
        - host: modiacontextholder.prod-fss-pub.nais.io
  env:
    - name: SYFOSMMANUELL_BACKEND_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmmanuell-backend/.default
    - name: SYFOSMMANUELL_BACKEND_URL
      value: http://syfosmmanuell-backend
    - name: MODIA_CONTEXT_SCOPE
      value: api://prod-fss.personoversikt.modiacontextholder/.default
    - name: MODIA_CONTEXT_URL
      value: https://modiacontextholder.prod-fss-pub.nais.io
