name: Deploy demo to nais labs
on:
  push:
    branches:
      - 'master'
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfosmmanuell:${{ github.sha }}
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps for client
        run: |
          npm install
        working-directory: ./client
      - name: Run tests for client
        env:
          CI: true
        run: |
          npm run test
        working-directory: ./client
      - name: Build client
        env:
          REACT_APP_NODE_ENV: development # Brukes siden det ikke er mulig å endre NODE_ENV manuelt
          REACT_APP_WEB_SERVER_URL: https://syfosmmanuell.dev.adeo.no/
          REACT_APP_HEAD_URL: https://navikt.github.io
          REACT_APP_GOSYS_URL: https://gosys.nais.preprod.local/gosys/bruker/brukeroversikt.jsf
        run: |
          npm run build
        working-directory: ./client
      - name: Install deps for server
        run: |
          npm install
        working-directory: ./server
      - name: Build server
        run: |
          npm run compile
        working-directory: ./server
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy app to labs gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: naiserator-demo.yaml
