name: Deploy to prod
on:
  push:
    branches:
      - master
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfosmmanuell:${{ github.sha }}
jobs:
  # JOB to run change detection
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Detect changed paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'server/**'
              - 'redis.yaml'
              - 'naiserator-prod.yaml'

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps for client
        run: |
          npm install
        working-directory: ./client
      - name: Run unit tests for client
        env:
          CI: true
        run: |
          npm test
        working-directory: ./client

  deploy-redis:
    name: Deploy redis to prod-fss
    needs: [changes, test]
    if: ${{ needs.changes.outputs.backend == 'true' }} # Only run on changes related to backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy Redis to prod-fss
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_TEAMSYKMELDING }}
          CLUSTER: prod-fss
          RESOURCE: redis.yaml

  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps for client
        run: |
          npm install
        working-directory: ./client
      - name: Build client
        env:
          NODE_ENV: production
          REACT_APP_HEAD_URL: https://app.adeo.no
          REACT_APP_GOSYS_URL: https://gosys-nais.nais.adeo.no/gosys/bruker/brukeroversikt.jsf
        run: |
          npm run build
        working-directory: ./client
      - name: Install deps for server
        run: |
          npm install
        working-directory: ./server
      - name: Build server
        run: |
          npm run compile
        working-directory: ./server
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy app to prod-fss
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_TEAMSYKMELDING }}
          CLUSTER: prod-fss
          RESOURCE: naiserator-prod.yaml
