name: Deploy to prod
on:
  push:
    branches:
      - master
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test -- --watchAll=false
      - name: Build
        env:
          REACT_APP_NODE_ENV: production
          REACT_APP_GET_MANUELLE_OPPGAVER_URL: https://syfosmmanuell.nais.adeo.no/backend/api/v1/hentManuellOppgave/?oppgaveid=
          REACT_APP_PUT_MANUELL_VURDERING_URL: https://syfosmmanuell.nais.adeo.no/backend/api/v1/vurderingmanuelloppgave/
          REACT_APP_GET_LOG_OUT_URL: https://syfosmmanuell.nais.adeo.no/logout
          REACT_APP_WEB_SERVER_URL: https://syfosmmanuell.nais.adeo.no/
        run: |
          npm run build
      - name: Create Docker tag
        env:
          NAME: syfosmmanuell
        run: |
          echo "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME" > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Build Docker image
        run: |
          docker build -t $(cat .docker_image):$(cat .docker_tag) .
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Push Docker image
        run: 'docker push $(cat .docker_image):$(cat .docker_tag)'
      #- name: deploy to prod-fss
      #  uses: navikt/deployment-cli/action@0.4.0
      #    env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    cluster: prod-fss
      #    team: teamsykefravr
      #    resources: naiserator-prod.yaml
