name: Deploy to prod
on:
  push:
    branches:
      - master
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfosmmanuell:${{ github.sha }}
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: |
          npm install
      #- name: Run tests
      #  run: |
      #    npm run test
      - name: Build
        env:
          REACT_APP_NODE_ENV: production
          REACT_APP_GET_MANUELLE_OPPGAVER_URL: https://syfosmmanuell.nais.adeo.no/backend/api/v1/hentManuellOppgave/?oppgaveid=
          REACT_APP_PUT_MANUELL_VURDERING_URL: https://syfosmmanuell.nais.adeo.no/backend/api/v1/vurderingmanuelloppgave/
          REACT_APP_GET_LOG_OUT_URL: https://syfosmmanuell.nais.adeo.no/logout
          REACT_APP_WEB_SERVER_URL: https://syfosmmanuell.nais.adeo.no/
        run: |
          npm run build
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
#      - name: Deploy to prod
#        uses: nais/deploy/actions/deploy@master
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-fss
#          RESOURCE: naiserator-prod.yaml
