name: Deploy to prod
on:
  push:
    branches:
      - master
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfosmmanuell-prod:${{ github.sha }}
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        run: |
          npm ci
      - name: Run unit tests
        run: |
          npm run test:ci
      - name: Lint
        run: |
          npm run lint

  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        run: |
          npm ci
      - name: Build app
        env:
          NODE_ENV: production
          NEXT_PUBLIC_GOSYS_URL: https://gosys.intern.nav.no/gosys/bruker/brukeroversikt.jsf
        run: |
          npm run build
        working-directory: ./client
      - name: Install deps for server
        run: |
          npm install
        working-directory: ./server
      - name: Build server
        run: |
          npm run compile
        working-directory: ./server
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy app to prod-fss
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_TEAMSYKMELDING }}
          CLUSTER: prod-fss
          RESOURCE: naiserator-prod.yaml
