name: Deploy to dev
on:
  push:
    branches:
      - '*'
      - '!master'
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfosmmanuell:${{ github.sha }}
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps for client
        run: |
          npm install
        working-directory: ./client
      - name: Run tests for client
        env:
          CI: true
        run: |
          npm run test
        working-directory: ./client
      - name: Build client
        env:
          REACT_APP_NODE_ENV: preprod # Brukes siden det ikke er mulig å endre NODE_ENV manuelt
          REACT_APP_GET_MANUELLE_OPPGAVER_URL: https://syfosmmanuell.nais.preprod.local/backend/api/v1/hentManuellOppgave/?oppgaveid=
          REACT_APP_PUT_MANUELL_VURDERING_URL: https://syfosmmanuell.nais.preprod.local/backend/api/v1/vurderingmanuelloppgave/
          REACT_APP_GET_LOG_OUT_URL: https://syfosmmanuell.nais.preprod.local/logout
          REACT_APP_WEB_SERVER_URL: https://syfosmmanuell.nais.preprod.local/
          REACT_APP_HEAD_URL: https://app-q1.adeo.no
          REACT_APP_GOSYS_URL: https://gosys.nais.preprod.local/gosys/bruker/brukeroversikt.jsf
        run: |
          npm run build
        working-directory: ./client
      - name: Install deps for server
        run: |
          npm install
        working-directory: ./server
      - name: Build server
        run: |
          npm run compile
        working-directory: ./server
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy Redis to preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: redis.yaml
      - name: Deploy app to preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator-dev.yaml
