name: Deploy to dev
on:
  push:
    branches:
      - '**'
      - '!master'
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
jobs:
  snyk-test:
    name: analyze dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --org=teamsykmelding --severity-threshold=high

  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: test, build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install deps
        run: |
          yarn --immutable
      - name: Run unit tests
        run: |
          yarn test:ci
      - name: Lint
        run: |
          yarn lint
      - name: Build app
        env:
          NODE_ENV: production
          NEXT_PUBLIC_GOSYS_URL: https://gosys-q1.dev.intern.nav.no/gosys/bruker/brukeroversikt.jsf
          NEXT_PUBLIC_ENVIRONMENT: dev
        run: |
          yarn build
      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamsykmelding
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
  deploy:
    name: deploy to dev
    needs: [snyk-test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy app to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_TEAMSYKMELDING }}
          CLUSTER: dev-gcp
          RESOURCE: naiserator-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}