name: Deploy to dev
on:
  push:
    branches:
      - '*'
      - '!master'
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfosmmanuell:${{ github.sha }}
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps for client
        run: |
          npm install
        working-directory: ./client
      - name: Run unit tests for client
        env:
          CI: true
        run: |
          npm test
        working-directory: ./client

  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps for client
        run: |
          npm install
        working-directory: ./client
      - name: Build client
        env:
          NODE_ENV: production
          REACT_APP_HEAD_URL: https://app-q1.dev.adeo.no
          REACT_APP_GOSYS_URL: https://gosys.nais.preprod.local/gosys/bruker/brukeroversikt.jsf
        run: |
          npm run build
        working-directory: ./client
      - name: Install deps for server
        run: |
          npm install
        working-directory: ./server
      - name: Build server
        run: |
          npm run compile
        working-directory: ./server
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy Redis to preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: redis.yaml
      - name: Deploy app to preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator-dev.yaml
